FROM gmathieu/node-browsers:3.0.0 AS build

COPY package.json /usr/mookh-agent/
WORKDIR /usr/mookh-agent
RUN npm install

COPY ./ /usr/mookh-agent
RUN npm run build

FROM nginx:1.15.8-alpine

## Remove default Nginx website
RUN rm -rf /usr/share/nginx/html/*

COPY ./scripts/nginx.conf /etc/nginx/nginx.conf

COPY --from=build  /usr/mookh-agent/dist/angular-docker /usr/share/nginx/html

RUN echo "mainFileName=\"\$(ls /usr/share/nginx/html/main*.js)\" && \
          envsubst '\$API_HOST \$DEFAULT_LANGUAGE ' < \${mainFileName} > main.tmp && \
          mv main.tmp  \${mainFileName} && nginx -g 'daemon off;'" > run.sh

ENTRYPOINT ["sh", "run.sh"]
